---
deployment:
  tasks:
    - export DEPLOYPATH=/home/trivalleyclinic/public_html
    - /bin/find $DEPLOYPATH/ -mindepth 1 -maxdepth 1 ! -name 'blog' ! -name 'deploy.php' ! -name 'webhook' ! -name '.well-known' -exec rm -rf {} +
    - /bin/cp -R /home/trivalleyclinic/repositories/TVC/dist/. $DEPLOYPATH/