---
deployment:
  tasks:
    - export REPO=/home/trivalleyclinic/repositories/TVC
    - export DEPLOYPATH=/home/trivalleyclinic/public_html
    - /bin/cp -R $REPO/dist/. $DEPLOYPATH/
    - /bin/cp -R $REPO/public/assets/. $DEPLOYPATH/assets/
    - /bin/cp $REPO/public/.htaccess $DEPLOYPATH/ 2>/dev/null; true